/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.com;

import java.util.Arrays;

import app.com.beans.DataA;
import app.com.beans.DataB;
import app.com.interfaces.ABMapper;

public class App {
    public String getGreeting() {
        return "Helloaa World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        
        DataA dataA = new DataA();
        dataA.setId(1);
        dataA.setName("Tarou");
        dataA.setAge(10);
        dataA.setDatas(new int[] {10, 11, 12});

        DataB b = ABMapper.INSTANCE.aToB(dataA);

        System.out.println(b.getNo());
        System.out.println(b.getNamae());
        System.out.println(b.getNenrei());
        System.out.println(Arrays.toString(b.getDatas()));
        
    }
}
